package vn.kalapa.demo.utils


object Common {
    val MY_KEY_TOKEN = "KLP_EKYC_KEY_TOKEN"
    val MY_KEY_LANGUAGE = "KLP_EKYC_KEY_LANGUAGE"
    val MY_KEY_LIVENESS_VERSION = "KLP_EKYC_KEY_LIVENESS_VERSION"
    val MY_KEY_MAIN_COLOR = "KLP_EKYC_KEY_MAIN_COLOR"
    val MY_KEY_BTN_TEXT_COLOR = "KLP_EKYC_KEY_BTN_TEXT_COLOR"
    val MY_KEY_MAIN_TEXT_COLOR = "KLP_EKYC_KEY_MAIN_TEXT_COLOR"
    val MY_KEY_BACKGROUND_COLOR = "KLP_EKYC_KEY_BACKGROUND_COLOR"
    val MY_KEY_ENV = "KLP_EKYC_KEY_ENVIRONMENT"

    val MY_KEY_CUSTOM_CAPTURE = "KLP_EKYC_KEY_CUSTOM_CAPTURE" // boolean
    val MY_KEY_CUSTOM_LIVENESS = "KLP_EKYC_KEY_CUSTOM_LIVENESS" // boolean
    val MY_KEY_CUSTOM_NFC = "KLP_EKYC_KEY_CUSTOM_NFC" // boolean

    val MY_KEY_UPGRADE_PLAN_FROM_SESSION_ID = "KLP_EKYC_UPGRADE_PLAN_FROM_SESSION_ID" // boolean

    val MY_KEY_SCENARIO = "KLP_EKYC_KEY_SCENARIO"
    val MY_KEY_MRZ = "KLP_EKYC_MRZ"
    val MY_KEY_LEFTOVER_SESSION = "KLP_EKYC_LEFTOVER_SESSION"
    val MY_KEY_FACE_DATA_URI = "KLP_EKYC_FACE_DATA_URI"
    val MY_KEY_ACCEPTED_DOCUMENT_1 = "KLP_EKYC_KEY_ACCEPTED_DOCUMENT_1"
    val MY_KEY_ACCEPTED_DOCUMENT_2 = "KLP_EKYC_KEY_ACCEPTED_DOCUMENT_2"
    val MY_KEY_ACCEPTED_DOCUMENT_3 = "KLP_EKYC_KEY_ACCEPTED_DOCUMENT_3"
    val MY_KEY_ACCEPTED_DOCUMENT_4 = "KLP_EKYC_KEY_ACCEPTED_DOCUMENT_4"
    val MY_KEY_ACCEPTED_DOCUMENT_5 = "KLP_EKYC_KEY_ACCEPTED_DOCUMENT_5"
    val MY_KEY_NFC_TIMEOUT_IN_SECONDS = "KLP_EKYC_KEY_NFC_TIMEOUT_IN_SECONDS"
    val MY_KEY_ENABLE_NFC = "KLP_EKYC_KEY_ENABLE_NFC"
    val MY_KEY_CAPTURE_IMAGE = "KLP_EKYC_KEY_CAPTURE_IMAGE"
    val MY_KEY_VERIFY_CHECK = "KLP_EKYC_KEY_VERIFY_CHECK"
    val MY_KEY_FRAUD_CHECK = "KLP_EKYC_KEY_FRAUD_CHECK"
    val MY_KEY_NORMAL_CHECK_ONLY = "KLP_EKYC_KEY_NORMAL_CHECK_ONLY"
    val MY_KEY_CARD_SIDE_CHECK = "KLP_EKYC_KEY_CARD_SIDE_CHECK"

    val MY_KEY_FACE_MATCHING_THRESHOLD = "KLP_EKYC_KEY_FACE_MATCHING_THRESHOLD" // int

}