package vn.kalapa.ekyc.utils

import android.content.Context
import vn.kalapa.ekyc.KalapaSDK
import java.util.Locale
import kotlin.collections.HashMap

class LanguageUtils(val activity: Context, private var mapLanguage: Map<String, String> = HashMap()) {
    fun setLanguage(map: Map<String, String>) {
//        for (k in map.keys) {
//            Helpers.printLog("Key $k: ${map[k]}")
//        }
        this.mapLanguage = map
    }

    fun getLanguageString(tag: String): String {
//        val string = Helpers.getStringPreferences(activity, tag)
//        Helpers.printLog("Get $tag: ${KalapaSDK.config.language}")
        val k = tag.lowercase(Locale.ROOT)
        return if (mapLanguage[k] != null) mapLanguage[k]!!
        else if (KalapaSDK.config.language.contains("vi") && VI_DEFAULT[k] != null)
            VI_DEFAULT[k]!!
        else if (KalapaSDK.config.language.contains("ko") && KO_DEFAULT[k] != null)
            KO_DEFAULT[k]!!
        else if (EN_DEFAULT[k] != null)
            EN_DEFAULT[k]!!
        else
            tag
    }

    private val EN_DEFAULT = mapOf(
        "klp_alert_title" to "Notice",
        "klp_done_title" to "Done",
        "klp_angle_not_correct" to "The angle of your face is not correct, please look straight",
        "klp_cancel" to "Cancel",
        "klp_cancel_button" to "Cancel",
        "klp_check_permission_camera" to "Please grant access to the camera to use this function.",
        "klp_check_permission_camera_title" to "Camera permission",
        "klp_confirm" to "Confirm",
        "klp_create_camera_error" to "The error occurred while initializing the rear camera, please try again later.",
        "klp_error_happen" to "Something went wrong",
        "klp_error_network" to "Connection lost, please inspect your network and try again.",
        "klp_error_nfc_card_lost_connection" to "Connection lost, please keep the card still until success.",
        "klp_error_nfc_not_enabled" to "Please turn on NFC to continue",
        "klp_error_nfc_wrong_id_card" to "Invalid ID",
        "klp_error_service_temporary_down" to "Server is busy, please retry.",
        "klp_error_unknown_short" to "Something went wrong, please retry.",
        "klp_guide_nfc_1" to "Your device supports NFC.",
        "klp_guide_nfc_2" to "You are using the chip-mounted identity card.",
        "klp_guide_nfc_3" to "Tap the chip to the NFC antenna on the back side of your device when the reader’s window appears.",
        "klp_guide_nfc_4" to "Keep the card still when the vibration occurs.",
        "klp_guide_nfc_position_1" to "The NFC location locates in the back of your device, please try moving the card slowly to find the correct spot.",
        "klp_guide_nfc_position_2" to "Keep the card still when the vibration occurs.",
        "klp_guide_title" to "Please make sure that:",
        "klp_guide_liveness_closer_face" to "Slowly move you face towards the camera",
        "klp_guide_liveness_no_face" to "Keep your face centered and within the camera frame",
        "klp_liveness_no_face" to "Unable to find any face",
        "klp_leave_confirm_content" to "Do you want to terminate the current process?",
        "klp_leave_confirm_title" to "Process termination!",
        "klp_liveness_error_timeout" to "Taking too long, please retry",
        "klp_liveness_guide_title" to "Please keep your face clearly visible and follow the instructions",
        "klp_liveness_look_straight" to "Look straight",
        "klp_liveness_processing_failed" to "Verification result: FAILED",
        "klp_liveness_processing_finish" to "Verification result: PASSED",
        "klp_liveness_tiltleft" to "Tilt left",
        "klp_liveness_tiltright" to "Tilt right",
        "klp_liveness_too_close" to "Your face is too close to the camera, please move a bit away",
        "klp_liveness_too_far" to "Your face is too far from the camera, please move closer a bit",
        "klp_liveness_too_many_faces" to "More than 1 face detected, please check",
        "klp_liveness_turndown" to "Turn down",
        "klp_liveness_turnleft" to "Turn left",
        "klp_liveness_turnright" to "Turn right",
        "klp_liveness_turnup" to "Turn up",
        "klp_message_nfc_ready" to "Ready to scan",
        "klp_next_btn" to "Continue",
        "klp_nfc_authentication" to "Reading data ...",
        "klp_nfc_common_error" to "There was a problem reading the chip, please try again.",
        "klp_nfc_connection_error" to "Connection error, please try again.",
        "klp_nfc_hold_still" to "Keep the card still until success.",
        "klp_nfc_invalid_mrz" to "Invalid MRZ.",
        "klp_nfc_more_one_tag_found" to "More than 1 device was found.",
        "klp_nfc_read_successfully" to "Success",
        "klp_nfc_request_present" to "Tap the chip to the back side of your device as illustrated",
        "klp_nfc_tag_not_valid" to "Invalid chip.",
        "klp_no" to "No",
        "klp_please_wait" to "Please wait...",
        "klp_retry_btn" to "Try again",
        "klp_scan_back_document" to "Please put the back-side of your card inside the highlighted frame.",
        "klp_scan_mrz" to "Scan the MRZ",
        "klp_timeout_body" to "Session has been expired, please retry.",
        "klp_title_liveness_detection" to "Liveness detection",
        "klp_toggle_flash_error" to "Unable to change flash state, please try again later.",
        "klp_yes" to "Yes",
        "klp_check_nfc_text" to "Check for NFC location",
        "klp_nfc_antenna_title" to "NFC LOCATION ON THIS DEVICE",
        "klp_nfc_start_button" to "Start",
        "klp_nfc_title" to "Verify electronic chip",
        "klp_not_support_nfc" to "This device does not support NFC",
        "klp_renew_nfc" to "Refreshing the NFC module, please wait...",
        "klp_guide_liveness_further_face" to "Please move a bit away",
        "klp_warning_title" to "Something went wrong",
        "klp_emulator_warning_body" to "This application is not allowed to run on emulators",
        "klp_virtual_camera_warning_body" to "Invalid camera settings",
        "klp_accept_btn" to "Accept"
    )
    private val VI_DEFAULT = mapOf(
        "klp_alert_title" to "Thông báo",
        "klp_angle_not_correct" to "Góc mặt chưa đúng, vui lòng nhìn thẳng",
        "klp_cancel" to "Huỷ",
        "klp_cancel_button" to "Hủy",
        "klp_check_nfc_text" to " Kiểm tra vị trí NFC",
        "klp_check_permission_camera" to "Vui lòng cho phép truy cập vào Camera để sử dụng chức năng này.",
        "klp_check_permission_camera_title" to "Truy cập vào Camera",
        "klp_confirm" to "Xác Nhận",
        "klp_create_camera_error" to "Đã xảy ra lỗi khi khởi tạo camera phía sau, vui lòng thử lại.",
        "klp_done_title" to "Xong",
        "klp_error_happen" to "Đã có lỗi xảy ra",
        "klp_error_network" to "Kết nối thất bại, vui lòng kiểm tra mạng và thử lại.",
        "klp_error_nfc_card_lost_connection" to "Mất kết nối thẻ, vui lòng chạm thẻ và giữ nguyên 5–6 giây cho đến khi hoàn thành",
        "klp_error_nfc_not_enabled" to "Vui lòng bật tính năng NFC để tiếp tục",
        "klp_error_nfc_wrong_id_card" to "Số CCCD không hợp lệ",
        "klp_error_service_temporary_down" to "Hệ thống đang gặp gián đoạn, vui lòng thử lại.",
        "klp_error_unknown_short" to "Đã có lỗi xảy ra, vui lòng thử lại.",
        "klp_guide_nfc_1" to "Thiết bị có hỗ trợ NFC.",
        "klp_guide_nfc_2" to "Đang sử dụng Căn cước công dân gắn chip.",
        "klp_guide_nfc_3" to "Chạm phần chip vào vị trí NFC phía sau điện thoại khi có cửa sổ thông báo hiện lên.",
        "klp_guide_nfc_4" to "Khi có tín hiệu rung, giữ nguyên thẻ cho tới khi có thông báo thành công.",
        "klp_guide_nfc_position_1" to "Vị trí NFC ở phía sau điện thoại, vui lòng chạm thẻ và di chuyển chậm để tìm điểm tiếp xúc.",
        "klp_guide_nfc_position_2" to "Khi có tín hiệu rung, giữ nguyên thẻ cho đến khi có thông báo thành công.",
        "klp_guide_title" to "Bạn chú ý đảm bảo:",
        "klp_guide_liveness_closer_face" to "Vui lòng di chuyển khuôn mặt lại gần camera",
        "klp_guide_liveness_no_face" to "Khuôn mặt đang quá sát viền camera, vui lòng chỉnh lại",
        "klp_liveness_no_face" to "Không tìm thấy khuôn mặt",
        "klp_leave_confirm_content" to "Bạn có chắc muốn thoát không?",
        "klp_leave_confirm_title" to "Thoát khỏi quá trình xác thực!",
        "klp_liveness_error_timeout" to "Quá thời gian thực hiện, vui lòng thực hiện lại",
        "klp_liveness_guide_title" to "Vui lòng để khuôn mặt nhìn rõ và làm theo hướng dẫn",
        "klp_liveness_look_straight" to "Vui lòng giữ mặt ngay ngắn và nhìn thẳng",
        "klp_liveness_processing_failed" to "Kết quả xác thực: THẤT BẠI",
        "klp_liveness_processing_finish" to "Kết quả xác thực: THÀNH CÔNG",
        "klp_liveness_tiltleft" to "Nghiêng sang trái",
        "klp_liveness_tiltright" to "Nghiêng sang phải",
        "klp_liveness_too_close" to "Khuôn mặt của bạn đang quá gần camera, vui lòng di chuyển ra xa một chút",
        "klp_liveness_too_far" to "Khuôn mặt của bạn đang quá xa camera, vui lòng di chuyển gần lại một chút",
        "klp_liveness_too_many_faces" to "Có nhiều hơn một khuôn mặt, vui lòng kiểm tra lại",
        "klp_liveness_turndown" to "Quay xuống dưới",
        "klp_liveness_turnleft" to "Quay sang trái",
        "klp_liveness_turnright" to "Quay sang phải",
        "klp_liveness_turnup" to "Quay lên trên",
        "klp_message_nfc_ready" to "Sẵn sàng quét chip",
        "klp_next_btn" to "Tiếp tục",
        "klp_nfc_antenna_title" to "VỊ TRÍ NFC TRÊN ĐIỆN THOẠI",
        "klp_nfc_authentication" to "Đang đọc dữ liệu trong chip ...",
        "klp_nfc_common_error" to "Đã xảy ra vấn đề khi đọc dữ liệu trong chip, vui lòng thử lại.",
        "klp_nfc_connection_error" to "Đã xảy ra lỗi kết nối, vui lòng thử lại.",
        "klp_nfc_hold_still" to "Vui lòng giữ nguyên thẻ cho đến khi nhận được thông báo thành công",
        "klp_nfc_invalid_mrz" to "MRZ không hợp lệ cho tài liệu này.",
        "klp_nfc_more_one_tag_found" to "Vui lòng chỉ sử dụng 1 thẻ.",
        "klp_nfc_read_successfully" to "Đọc thành công.",
        "klp_nfc_request_present" to "Chạm chip vào mặt sau của thiết bị như đã được hướng dẫn.",
        "klp_nfc_start_button" to "Bắt đầu xác thực",
        "klp_nfc_tag_not_valid" to "Chip không hợp lệ.",
        "klp_nfc_title" to "Xác thực chip điện tử",
        "klp_no" to "Không",
        "klp_not_support_nfc" to "Thiết bị không hỗ trợ NFC",
        "klp_please_wait" to "Đang tải ...",
        "klp_renew_nfc" to "Đang làm mới NFC, vui lòng đợi ...",
        "klp_retry_btn" to "Thử lại",
        "klp_scan_back_document" to "Vui lòng đặt thẻ vào trong khung trên màn hình và giữ cho thẻ nhìn rõ.",
        "klp_scan_mrz" to "Quét MRZ trên mặt sau thẻ",
        "klp_timeout_body" to "Phiên làm việc đã hết hạn, vui lòng thực hiện lại.",
        "klp_title_liveness_detection" to "Xác thực chân dung",
        "klp_toggle_flash_error" to "Không thể thay đổi trạng thái flash, vui lòng thử lại.",
        "klp_yes" to "Có",
        "klp_guide_liveness_further_face" to "Vui lòng di chuyển ra xa một chút",
        "klp_warning_title" to "Có lỗi xảy ra",
        "klp_emulator_warning_body" to "Ứng dụng không được phép chạy trên máy ảo",
        "klp_virtual_camera_warning_body" to "Camera không hợp lệ",
        "klp_accept_btn" to "Đồng Ý"
    )

    private val KO_DEFAULT = mapOf(
        "klp_alert_title" to "공지",
        "klp_angle_not_correct" to "얼굴 각도가 올바르지 않습니다, 정면을 바라봐 주세요",
        "klp_cancel" to "취소",
        "klp_cancel_button" to "취소",
        "klp_check_nfc_text" to "NFC 위치 확인",
        "klp_check_permission_camera" to "이 기능을 사용하려면 카메라에 대한 접근 권한을 부여해 주세요.",
        "klp_check_permission_camera_title" to "카메라 권한",
        "klp_confirm" to "확인",
        "klp_create_camera_error" to "후면 카메라를 초기화하는 동안 오류가 발생했습니다, 나중에 다시 시도해 주세요.",
        "klp_done_title" to "완료",
        "klp_error_happen" to "문제가 발생했습니다",
        "klp_error_network" to "연결이 끊어졌습니다, 네트워크를 점검하고 다시 시도해 주세요.",
        "klp_error_nfc_card_lost_connection" to "연결이 끊어졌습니다, 성공할 때까지 카드를 그대로 두세요.",
        "klp_error_nfc_not_enabled" to "계속하려면 NFC를 켜주세요",
        "klp_error_nfc_wrong_id_card" to "잘못된 ID",
        "klp_error_service_temporary_down" to "서버가 바쁩니다, 다시 시도해 주세요.",
        "klp_error_unknown_short" to "문제가 발생했습니다, 다시 시도해 주세요.",
        "klp_guide_nfc_1" to "기기가 NFC를 지원합니다.",
        "klp_guide_nfc_2" to "칩이 장착된 신분증 카드를 사용하고 있습니다.",
        "klp_guide_nfc_3" to "리더기 창이 나타나면 칩을 기기 뒷면의 NFC 안테나에 탭하세요.",
        "klp_guide_nfc_4" to "진동이 일어나면 카드를 그대로 두세요.",
        "klp_guide_nfc_position_1" to "NFC 위치는 기기의 뒷면에 있습니다, 올바른 위치를 찾기 위해 카드를 천천히 움직여 보세요.",
        "klp_guide_nfc_position_2" to "진동이 일어나면 카드를 그대로 두세요.",
        "klp_guide_title" to "다음을 확인해 주세요:",
        "klp_guide_liveness_closer_face" to "카메라를 향해 천천히 얼굴을 움직여 주세요",
        "klp_guide_liveness_no_face" to "얼굴을 중앙에 두고 카메라 프레임 내에 있도록 유지하세요",
        "klp_liveness_no_face" to "얼굴을 찾을 수 없습니다.",
        "klp_leave_confirm_content" to "현재 과정을 종료하시겠습니까?",
        "klp_leave_confirm_title" to "과정 종료!",
        "klp_liveness_error_timeout" to "너무 오래 걸립니다, 다시 시도해 주세요",
        "klp_liveness_guide_title" to "얼굴을 명확하게 보이게 하고 지시사항을 따르세요",
        "klp_liveness_look_straight" to "정면을 바라봐 주세요",
        "klp_liveness_processing_failed" to "검증 결과>실패",
        "klp_liveness_processing_finish" to "검증 결과>통과",
        "klp_liveness_tiltleft" to "왼쪽으로 기울이세요",
        "klp_liveness_tiltright" to "오른쪽으로 기울이세요",
        "klp_liveness_too_close" to "얼굴이 카메라에 너무 가깝습니다, 조금 뒤로 가세요",
        "klp_liveness_too_far" to "얼굴이 카메라에서 너무 멀리 떨어져 있습니다, 조금 가까이 오세요",
        "klp_liveness_too_many_faces" to "1개 이상의 얼굴이 감지되었습니다, 확인해 주세요",
        "klp_liveness_turndown" to "아래로 돌리세요",
        "klp_liveness_turnleft" to "왼쪽으로 돌리세요",
        "klp_liveness_turnright" to "오른쪽으로 돌리세요",
        "klp_liveness_turnup" to "위로 돌리세요",
        "klp_message_nfc_ready" to "스캔 준비 완료",
        "klp_next_btn" to "계속",
        "klp_nfc_antenna_title" to "이 기기의 NFC 위치",
        "klp_nfc_authentication" to "데이터 읽는 중 ...",
        "klp_nfc_common_error" to "칩을 읽는 중 문제가 발생했습니다, 다시 시도해 주세요.",
        "klp_nfc_connection_error" to "연결 오류, 다시 시도해 주세요.",
        "klp_nfc_hold_still" to "성공할 때까지 카드를 그대로 두세요.",
        "klp_nfc_invalid_mrz" to "잘못된 MRZ.",
        "klp_nfc_more_one_tag_found" to "1개 이상의 장치가 발견되었습니다.",
        "klp_nfc_read_successfully" to "성공",
        "klp_nfc_request_present" to "도면에 표시된 대로 기기의 뒷면에 칩을 탭하세요",
        "klp_nfc_start_button" to "시작",
        "klp_nfc_tag_not_valid" to "잘못된 칩.",
        "klp_nfc_title" to "전자 칩 검증",
        "klp_no" to "아니요",
        "klp_not_support_nfc" to "이 기기는 NFC를 지원하지 않습니다",
        "klp_please_wait" to "잠시만 기다려 주세요...",
        "klp_renew_nfc" to "NFC 모듈을 새로 고치는 중, 잠시만 기다려 주세요...",
        "klp_retry_btn" to "다시 시도",
        "klp_scan_back_document" to "카드의 뒷면을 강조 표시된 프레임 안에 넣어 주세요.",
        "klp_scan_mrz" to "MRZ 스캔",
        "klp_timeout_body" to "세션이 만료되었습니다, 다시 시도해 주세요.",
        "klp_title_liveness_detection" to "얼굴 검증",
        "klp_toggle_flash_error" to "플래시 상태를 변경할 수 없습니다, 나중에 다시 시도해 주세요.",
        "klp_yes" to "예",
        "klp_guide_liveness_further_face" to "조금 뒤로 가세요",
        "klp_warning_title" to "문제가 발생했습니다",
        "klp_emulator_warning_body" to "이 애플리케이션은 에뮬레이터에서 실행할 수 없습니다",
        "klp_virtual_camera_warning_body" to "카메라 설정이 잘못되었습니다",
        "klp_accept_btn" to "수락"
    )
}